language: node_js

deploy:
  - provider: s3
    access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}

  - provider: codedeploy
    access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ap-southeast-1
    bucket: duck-codedeploy
    key: latest/duck.zip
    application: duck
    deployment_group: duck-deployment
    on:
      branch: master