language: node_js
node_js: 10

before_install:
  - npm install -g yarn

install:
  - yarn install

script: 
  echo "run script :)"

deploy:
  - provider: s3
    access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    bucket: duck-codedeploy
    local_dir: src
    skip_cleanup: true
    on:
      branch: master

  - provider: codedeploy
    access_key_id: ${AWS_S3_ACCESS_KEY_ID}
    secret_access_key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: ap-southeast-1
    bucket: duck-codedeploy
    key: latest/duck.zip
    application: duck
    deployment_group: duck-deployment
    on:
      branch: master